import localFont from 'next/font/local';
import './globals.css';
import Navbar from '../Component/Navbar';
import { ThemeProvider } from '../Component/theme-provider';
import Footer from '../Component/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Next.js Blogs',
  description: 'Generated by create next app',
  keywords: ['next.js', 'blog', 'cms'],
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className='max-w-6xl mx-auto px-4 mt-4 '>{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
